version: "1"

services:
  worldgen:
    container_name: worldgen
    hostname: worldgen
    build: Dockerfile
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./outputs:/outputs
      - ./data:/data
